---
version: "3"
services:
  app:
    build:
      context: .
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
    ports:
      - 1323:1323
    environment:
      - GITBUCKET_URL
      - GITLAB_URL

